data         1
read_int     0
ld_var       0
ld_int      10
lt           0
jmp_false    9
ld_int       1
store        1
goto         9
ld_var       0
ld_int      10
lt           0
jmp_false   22
ld_int       5
ld_var       1
mult         0
store        1
ld_var       0
ld_int       1
add          0
store        0
goto         9
ld_var       0
write_int    0
ld_var       1
write_int    0
halt         0
